#!/usr/bin/env php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Nette\PhpGenerator\ClassType;
use Nette\PhpGenerator\InterfaceType;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\PsrPrinter;

const EXPR_DIR = __DIR__ . '/../src/Expr';
const STMT_DIR = __DIR__ . '/../src/Stmt';

defineAst(EXPR_DIR, 'Expr', [
    'Assign   : Lox\Token name, Lox\Expr\Expr value',
    'Binary   : Lox\Expr\Expr left, Lox\Token operator, Lox\Expr\Expr right',
    'Grouping : Lox\Expr\Expr expression',
    'Literal  : value',
    'Unary    : Lox\Token operator, Lox\Expr\Expr right',
    'Variable : Lox\Token name',
]);

// Stmt classes must have Stmt suffix to be valid
defineAst(STMT_DIR, 'Stmt', [
    'BlockStmt      : List<Stmt> statements',
    'ExpressionStmt : Lox\Expr\Expr expression',
    'PrintStmt      : Lox\Expr\Expr expression',
    'VarStmt        : Lox\Token name, ?Lox\Expr\Expr initializer',
]);

function defineAst(string $outputDir, string $baseName, array $types): void
{
    if (!is_dir($outputDir)) {
        mkdir($outputDir);
    }

    $baseClass = generateBaseClass($baseName);
    writeClass($outputDir, $baseName, $baseClass);

    $visitorInterface = generateVisitor($baseName, $types);
    writeClass($outputDir, $baseName, $visitorInterface);

    foreach ($types as $type) {
        $parts = explode(':', $type);
        $className = trim($parts[0]);
        $propertiesAsString = trim($parts[1]);

        $properties = explode(',', $propertiesAsString);

        $typeClass = generateType($baseName, $className, $properties);
        writeClass($outputDir, $baseName, $typeClass);
    }
}

function generateBaseClass(string $baseName): ClassType
{
    $class = new ClassType($baseName);
    $class->setAbstract();

    $method = $class->addMethod('accept');
    $method->setAbstract();
    $param = $method->addParameter('visitor');
    $param->setType(sprintf('\Lox\%s\Visitor', $baseName));

    return $class;
}

function generateVisitor(string $baseName, array $types): InterfaceType
{
    $class = new InterfaceType('Visitor');

    foreach ($types as $type) {
        $parts = explode(':', $type);
        $typeName = trim($parts[0]);

        if ('Stmt' === $baseName) {
            // because Stmt classes already have Stmt suffix
            $method = $class->addMethod(sprintf('visit%s', $typeName));
            $method->setReturnType('void');
        } else {
            $method = $class->addMethod(sprintf('visit%s%s', $typeName, $baseName));
        }
        $method->setVisibility('public');
        $param = $method->addParameter(strtolower($baseName));
        $param->setType(sprintf('Lox\%s\%s', $baseName, $typeName));
    }

    return $class;
}

function generateType(string $baseName, string $className, array $properties = []): ClassType
{
    $class = new ClassType($className);
    $class->setExtends(sprintf('\Lox\%s\%1$s', $baseName));
    $class->setFinal();

    $constructor = $class->addMethod('__construct');

    foreach ($properties as $property) {
        $parts = explode(' ', trim($property));

        $type = 'mixed';
        $propertyComment = null;
        $constructorComment = null;
        $returnComment = null;
        if (isset($parts[1])) {
            $type = $parts[0];
            $propertyName = $parts[1];

            if (preg_match('/^List<.*>$/', $type)) {
                $propertyComment = sprintf('@var %s', lcfirst($type));
                $constructorComment = sprintf('@param %s $%s', lcfirst($type), $propertyName);
                $returnComment = sprintf('@return %s', lcfirst($type));
                $type = 'array';
            }
        } else {
            $propertyName = $parts[0];
        }

        // add property
        $property = $class->addProperty($propertyName);
        $property->setVisibility('private');
        $property->setType($type);
        if (null !== $propertyComment) {
            $property->setComment($propertyComment);
        }

        // add constructor parameter and init property
        $parameter = $constructor->addParameter($propertyName);
        $parameter->setType($type);
        $constructor->addBody('$this->? = $?;', [$propertyName, $propertyName]);
        if (null !== $constructorComment) {
            $constructor->addComment($constructorComment);
        }

        // add getter
        $getter = $class->addMethod($propertyName);
        $getter->setReturnType($type);
        $getter->addBody('return $this->?;', [$propertyName]);
        if (null !== $returnComment) {
            $getter->addComment($returnComment);
        }
    }

    // implements accept method
    $method = $class->addMethod('accept');
    $method->addAttribute('Override');
    $param = $method->addParameter('visitor');
    $param->setType(sprintf('\Lox\%s\Visitor', $baseName));

    if (strpos($className, $baseName)) {
        $method->addBody(sprintf('return $visitor->visit%s($this);', $className));
    } else {
        $method->addBody(sprintf('return $visitor->visit%s%s($this);', $className, $baseName));
    }

    return $class;
}

function writeClass(string $outputDir, string $baseName, ClassType|InterfaceType $class): void
{
    $file = new PhpFile();
    $file->addComment('This file is auto-generated.');
    $file->setStrictTypes();

    $namespace = $file->addNamespace(sprintf('Lox\%s', $baseName));
    $namespace->add($class);

    if ($class instanceof ClassType && $class->hasMethod('__construct')) {
        $constructor = $class->getMethod('__construct');
        foreach ($constructor->getParameters() as $parameter) {
            if (null !== $parameter->getType() && !in_array($parameter->getType(), $namespace->getUses()) && str_contains((string) $parameter->getType(), '\\')) {
                $namespace->addUse((string) $parameter->getType());
            }
        }
    }

    $className = $class->getName();
    if (null === $className) {
        throw new \InvalidArgumentException('Class or Interface must have a name.');
    }

    file_put_contents(
        sprintf('%s/%s.php', $outputDir, $className),
        (new PsrPrinter())->printFile($file)
    );
}
